### ISSUE TITLE
Having an issue getting started....

### ISSUE THREAD

**Issue by GeekRuthie** [gryphonshafer/Bot-IRC#11]
I'm having a bit of trouble getting the bot breathing.  Here's my call to Bot::IRC:

`my $BOT_HOME = "/home/geekruthie/bot";

my $bot = Bot::IRC->new(
   spawn  => 2,
   daemon => {
      name        => 'AnneBot',
      lsb_sdesc   => 'Anne IRC Bot',
      pid_file    => "$BOT_HOME/AnneBot.pid",
      stderr_file => "$BOT_HOME/AnneBot.err",
      stdout_file => "$BOT_HOME/AnneBot.log",
   },  
   connect => {
      server => 'redacted',
      port   => '6667',
      nick   => 'Anne',
      name   => 'Anne IRC Bot',
      ssl    => 0,
      ipv6   => 0,
      join   => ['#bottest'],
   },  
   plugins => [ 'Store::SQLite', ':core' ],
   vars    => {
      store => "$BOT_HOME/AnneBot.sqlite",
   },  
)->run('/msg GeekRuthie Why did you wake me?');
`
On startup, it's neither joining #bottest, or messaging me; it *looks* like I'm doing this right, according to the docs, but it's not happening. Otherwise it starts up just fine, as far as I can tell.  If I message Anne privately, and tell it to join some channel, it will...but it won't come back on restart, even though I can see the stored information in the sqlite file. There is nothing in the error file.  Any idea what I'm doing wrong here?

**Comment by gryphonshafer** [comment]
Hm, looks like what you have there should work. I got it to work for me, although I made a slight change to the 1 command you pass into `run()`. Here's my program exactly:

    #!/usr/bin/env perl
    use exact;
    use Bot::IRC;

    my $BOT_HOME = "/home/gryphon/spike";

    my $bot = Bot::IRC->new(
        spawn  => 2,
        daemon => {
            name        => 'AnneBot',
            lsb_sdesc   => 'Anne IRC Bot',
            pid_file    => "$BOT_HOME/AnneBot.pid",
            stderr_file => "$BOT_HOME/AnneBot.err",
            stdout_file => "$BOT_HOME/AnneBot.log",
        },
        connect => {
            server => 'irc.perl.org',
            port   => '6667',
            nick   => 'Anne',
            name   => 'Anne IRC Bot',
            ssl    => 0,
            ipv6   => 0,
            join   => ['#bottest'],
        },
        plugins => [ 'Store::SQLite', ':core' ],
        vars    => {
            store => "$BOT_HOME/AnneBot.sqlite",
        },
    )->run('PRIVMSG gryphon :Why did you wake me?');

If this doesn't work for you exactly as-is, check the log file. Is there anything in the log file that might hint at a problem? I'll typically tail the log for the few seconds it takes for the connection to establish. Maybe there's a clue in there. Another idea is that maybe you've got an old dependency somewhere. Maybe try a fresh of your dependencies. I use `perlbrew` to start with a clean library set to ensure I have most current versions of everything.

**Comment by GeekRuthie** [comment]
Nothing in the log gives any hint of trouble.  I'll brew a fresh perl, and install fresh with dependencies, and see if that's it.

**Comment by GeekRuthie** [comment]
Okay, I've maybe narrowed it down some--it works fine for irc.perl.org, but not for our internal one, which is an ngircd-23 server.  Either something amiss with that server, or something in the settings on the IRCD.  I'll chase that angle.

**Comment by GeekRuthie** [comment]
PR #12 fixes what I figured out here; irc.perl.org doesn't send the 001 as its first message, but our private IRC does.

**Comment by gryphonshafer** [comment]
Awesome. Thanks for the PR.
