### ISSUE TITLE
$bot->run dies on interrupted connection.

### ISSUE THREAD

**Issue by eleksir** [gryphonshafer/Bot-IRC#15]
I'm expecting that bot returns from $bot->run statement (hopefully with $! set, but if isn't - i can live with it) when irc server restarts (or connection timeouts or something else bad network-related occurs), so i can do something like:
```perl
do {
    my $result = eval { $bot->run; };
    warn $@ . "\n";
} while (sleep 5);
```
but now it just dies effectively denying ability to catch this event and re ->run() framework.

**Comment by gryphonshafer** [comment]
Bot::IRC in an initialization program creates a parent process which spawns child processes. The initialization program is a different process than the parent and its children, so wrapping `run()` doesn't make sense. Instead, when the parent shuts down (like from a dropped connection), there needs to be something monitoring to restart it or the parent needs to signal that it's shutting down. Commit 70e944d adds a `disconnect` parameter that you can supply with a subref for that purpose.
