### ISSUE TITLE
worker process still running after master is exited/crashed.

### ISSUE THREAD

**Issue by eleksir** [gryphonshafer/Bot-IRC#17]
After crashing in gryphonshafer/Bot-IRC#16 there are couple children process still persists.

```bash
bash-5.1$ ps xa|grep irc
56288 unit      0:00 {/var/lib/aleesa} /var/lib/aleesa-irc-bot/bin/aleesa-irc-bot
56289 unit      0:00 {/var/lib/aleesa} /var/lib/aleesa-irc-bot/bin/aleesa-irc-bot
bash-5.1$ 
```

Aren't they should somehow reaped?

**Comment by gryphonshafer** [comment]
I don't think this is anything Bot::IRC can handle itself. If the master process exits normally, it'll close all the children. If it crashes (or hangs and has to be manually killed), then the children need to be manually killed off.
