### ISSUE TITLE
ERROR :Registration timeout: 1m0s

### ISSUE THREAD

**Issue by ghost** [gryphonshafer/Bot-IRC#3]
Hi!

I'm trying to figure out why YABOT doesn't connect to my oragono 1.10 server.
This is the sample code I use to get YABOT going:
```
#!/usr/bin/perl
use Bot::IRC;

Bot::IRC->new(
    spawn  => 2,
    daemon => {
        name        => 'bot',
        lsb_sdesc   => 'Yet Another IRC Bot',
        pid_file    => 'bot.pid',
        stderr_file => 'bot.err',
        stdout_file => 'bot.log',
    },
    connect => {
        server => 'irc.ccmiddelburg.nl',
        port   => '6667',
        nick   => 'yabot',
        name   => 'Yet Another IRC Bot',
        join   => [ '#welkom', '#ACME' ],
        ssl    => 0,
    },
    plugins => [],
    vars    => {},
)->run;
```
If I enter `irc.efnet.nl` as the server, it successfully connects to efnet...

Telnetting to irc.ccmiddelburg.nl 6667 from the same machine works as well:
<img width="944" alt="Schermafbeelding 2019-07-06 om 19 58 03" src="https://user-images.githubusercontent.com/13683523/60759617-7abf3c80-a028-11e9-91c3-347fa291d9a0.png">

I might be wrong for raising an issue here, as it very well could be a config mistake I made in my oragono ircd.yaml file. However I thought it strange that yabot wouldn't join a channel whereas telnetting and issuing the same commands is no problem! What could be going on?

kind regards

**Comment by gryphonshafer** [comment]
Resolved in v1.24 115ebfe. I ended up adding an optional parameter so that if anybody is depending on the legacy behavior, they can get that behavior, but the default new behavior resolves this bug.
