### ISSUE TITLE
karma help == seen help

### ISSUE THREAD

**Issue by ghost** [gryphonshafer/Bot-IRC#5]
Hello Gryphon,

Just a small issue, I noticed the help on the karma add-on is talking about the seen command:

https://github.com/gryphonshafer/Bot-IRC/blob/115ebfe17c7af756ebac61a49080b4eb20fa7be9/lib/Bot/IRC/Karma.pm#L77

best regards,

**Comment by gryphonshafer** [comment]
Resolved with adee364 and released in [v1.25](https://github.com/gryphonshafer/Bot-IRC/releases/tag/v1.25).
